### ISSUE TITLE
Method declared in FirebaseAPI.h file but NOT defined in .m

### ISSUE THREAD

**Issue by JimCampagno** [learn-co-curriculum/ios-deployOnDayOne-Advanced#2]
- (void)loginExistingUser; This method is declared in the Firebase.h file but not defined in the .m file

https://github.com/learn-co-curriculum/ios-deployOnDayOne-Advanced/blob/master/deployOnDayOne/FirebaseAPI.h#L17

**Comment by AnnJohn** [comment]
Closing issue. Lab deprecated
