### ISSUE TITLE
motion to deprecate; lab is un-doable

### ISSUE THREAD

**Issue by tomalley104** [learn-co-curriculum/ios-deployOnDayOne-Advanced#3]
the firebase API client isnt done and at no point in the course (as a student) did it feel like it made sense to go back and try to finish it

**Comment by AnnJohn** [comment]
@TOMalley104 @jmburges @markedwardmurray I'd like to deprecate this lab. Can you all get back to me by EOW 8/21/2015 otherwise I'll deprecate this lab.

**Comment by jmburges** [comment]
@AnnJohn deprecate away

**Comment by markedwardmurray** [comment]
:penguin:

**Comment by AnnJohn** [comment]
Deprecated lab and closing issue
